image: node:20

pipelines:
  default:
        - step:
            name: Install Yarn and Package Modules
            caches:
              - nodemodulescache
              - yarncache
            script:
              - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.19
              - export PATH=$HOME/.yarn/bin:$PATH
              - yarn install --frozen-lockfile
        - step:
            name: Build Application
            caches:
              - dist
            script:
              - yarn build
        - step:
            name: Jest Testing
            script:
              - yarn test
            caches:
              - dist
        - parallel:
          - step: 
              name: Run Linter
              script:
                - yarn lint:watch
          - step:
              name: Check Branch Linter
              script:
                - yarn branchlint
        - step: 
            name: Release Changelog
            script:
              - yarn release        

definitions:
  caches:
    nodemodulescache: ./node_modules
    yarncache: /usr/local/share/.cache/yarn/
    dist: ./dist