image: node:20

pipelines:
  default:
    - parallel:
        - step:
            name: Install Yarn and Package Modules
            caches:
              - nodemodulescache
              - yarncache
            script:
              - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
              - export PATH=$HOME/.yarn/bin:$PATH
              - yarn
              - yarn build
        - step:
            name: Jest Testing
            script:
              - yarn test
            caches:
              - yarncache
        - step: 
            name: Run Linter
            script:
              - yarn lint:watch
            caches:
              - yarncache
        - step:
            name: Check Branch Linter
            script:
              - yarn branchlint
        - step: 
            name: Release Changelog
            script:
              - yarn release
            caches:
              - yarncache             
definitions:
  caches:
    nodemodulescache: ./node_modules
    yarncache: /usr/local/share/.cache/yarn/