image: node:20

pipelines:
  default:
    - parallel:
        - step:
            name: Install Yarn and Package Modules
            caches:
              - node
            script:
              - npm install yarn
              - yarn install
        - step:
            name: Jest Testing
            script:
              - yarn test
            caches:
              - node
        - step: 
            name: Run Linter
            script:
              - yarn lint:watch
            caches:
              - node
        - step:
            name: Check Branch Linter
            script:
              - yarn branchlint
        - step: 
            name: Release Changelog
            script:
              - yarn release
            caches:
              - node             
