image: node:20

pipelines:
  default:
        - step:
            name: Install Yarn and Package Modules
            script:
              - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.19
              - export PATH=$HOME/.yarn/bin:$PATH
              - yarn install --frozen-lockfile
              - yarn add global @nestjs/cli
        - step:
            name: Build Application
            script:
              - yarn build
        - step:
            name: Jest Testing
            script:
              - yarn test
        - step: 
            name: Run Linter
            script:
              - yarn lint:watch
        - step: 
            name: Release Changelog
            script:
              - yarn release        
